name: Publish Bot

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install npm packages
      run: npm ci
    - name: Build frontend bundle
      run: npm run build

    - name: Upload to server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.davidday.tw
        username: self-diagnose@davidday.tw
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          .env*
          **/.git*
          **/.git*/**
          **/node_modules/**
          vendor/**

    - name: Execute deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/Self-Diagnosis
          php artisan down

          chmod -R 777 storage bootstrap/cache
          rm -rf ./vendor
          /opt/cpanel/composer/bin/composer install --optimize-autoloader --no-dev
          
          php artisan storage:link
          php artisan migrate --force
          php artisan up
